### PR TITLE
Add `calculateHash`, change post signature

### PR DESCRIPTION
**Pull request by ajacksified**
:eyeglasses: @spladug @umbrae 

Split out calculateHash beacuse mweb will use the hmac code from node, and desktop will use... whatever desktop uses.

### CODE REVIEW

**Comment by umbrae** [comment]
So, when calculating the hash, we're going to need to generate the serialized version of the request body in order to have the proper hash. And then additionally the `post` function will be re-serializing the data in its own logic, right? That seems like a place for a disconnect between the hash and the data to occur and is maybe not great. (If I'm understanding properly).

I wonder if there's a way that we can have the serialization of the request body all be in one place so that we can generate the hmac with confidence?

**Comment by umbrae** [comment]
:nail_care: for thoughts on that

**Comment by ajacksified** [comment]
@umbrae in theory, it could be different, if you modify the body in the `post` or if you use a broken serializer, but in practice, it's not an actual issue. And, if it is, it will helpfully throw errors and reject in the event your serializer _is_ broken.

I could expose the `body` directly instead of `JSON.stringify(body)` in calculateHash and you can implement the serialization yourself using the same serializer that your `post` function does, to be safe, although any function we use is just going to use `JSON.serialize` anyway.

If you feel strongly about the error case, I can go with the second option.

**Comment by umbrae** [comment]
:fish: I think we can try this.

**Pull request merged**
